import type { Product, ProductDetails } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Maan Lämpö",
    image: "/earthy-warm-abstract-organic.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Maanläheiset sävyt ja orgaaniset muodot luovat rauhallisen tunnelman",
  },
  {
    id: 2,
    name: "Luonnon Kosketus",
    image: "/organic-botanical-warm-tones.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Kasviaiheinen abstraktio lämpimissä ruskeissa ja oransseissa sävyissä",
  },
  {
    id: 3,
    name: "Rohkea Geometria",
    image: "/bold-geometric-vibrant-retro.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Värikäs retro-geometria eloisilla muodoilla ja rohkeilla väreillä",
  },
  {
    id: 4,
    name: "Dynaaminen Liike",
    image: "/dynamic-bold-circular-modern.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Moderni abstraktio dynaamisilla ympyröillä ja kaarevilla muodoilla",
  },
  {
    id: 5,
    name: "Yoshino Vuori",
    image: "/yoshino-mountain-cherry-blossom.webp",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Japanilainen vintage-juliste kirsikankukkavuoresta",
  },
  {
    id: 6,
    name: "Auringonlaskun Lämpö",
    image: "/warm-sunset-geometric-abstract.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Lämmin geometrinen abstraktio auringonlaskun väreissä",
  },
  {
    id: 7,
    name: "Kukkien Tuoksu",
    image: "/green-flowers-quirky-text-art.webp",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Leikkisä moderni taide vihreine kukkineen ja hauskalla tekstillä",
  },
  {
    id: 8,
    name: "Retro Väriloisto",
    image: "/retro-colorful-geometric-shapes.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Värikäs retro-abstraktio geometrisilla muodoilla",
  },
  {
    id: 9,
    name: "Moderni Värimaailma",
    image: "/modern-bold-overlapping-abstract.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Moderni abstrakti teos päällekkäisillä muodoilla ja rohkeilla väreillä",
  },
  {
    id: 10,
    name: "Rauhallinen Tila",
    image: "/calm-minimalist-soft-shapes.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Minimalistinen teos pehmeillä muodoilla ja rauhallisilla sävyillä",
  },
  {
    id: 11,
    name: "Pehmeä Harmonia",
    image: "/soft-minimalist-neutral-circles.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Minimalistinen abstraktio pehmeillä ympyröillä ja neutraaleilla sävyillä",
  },
  {
    id: 12,
    name: "Terrakotta Unelma",
    image: "/vintage-terracotta-warm-abstract.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Vintage-tyylinen abstraktio lämpimissä terrakotta- ja ruskeissa sävyissä",
  },
  {
    id: 13,
    name: "Värien Juhla",
    image: "/vibrant-colorful-geometric-retro.avif",
    price: "12,90 €",
    priceInCents: 1290,
    description: "Rohkea retro-juliste eloisilla väreillä ja geometrisilla muodoilla",
  },
]

export const productDetails: Record<number, ProductDetails> = {
  1: {
    images: ["/earthy-warm-abstract-organic.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Maanläheiset lämpimät sävyt",
      "Orgaaniset virtaavat muodot",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  2: {
    images: ["/organic-botanical-warm-tones.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Kasviaiheinen abstraktio",
      "Lämpimät ruskeat ja oranssit sävyt",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  3: {
    images: ["/bold-geometric-vibrant-retro.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Rohkeat geometriset muodot",
      "Eloisat retro-värit",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  4: {
    images: ["/dynamic-bold-circular-modern.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Dynaamiset ympyrämuodot",
      "Moderni abstrakti tyyli",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  5: {
    images: ["/yoshino-mountain-cherry-blossom.webp"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Japanilainen vintage-juliste",
      "Kirsikankukat ja vuorimaisema",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  6: {
    images: ["/warm-sunset-geometric-abstract.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Lämmin geometrinen abstraktio",
      "Auringonlaskun väripaletti",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  7: {
    images: ["/green-flowers-quirky-text-art.webp"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Leikkisä moderni taide",
      "Vihreät käsinpiirretyt kukat",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  8: {
    images: ["/retro-colorful-geometric-shapes.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Värikäs retro-abstraktio",
      "Geometriset muodot",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  9: {
    images: ["/modern-bold-overlapping-abstract.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Moderni abstrakti taide",
      "Päällekkäiset muodot",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  10: {
    images: ["/calm-minimalist-soft-shapes.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Rauhallinen minimalismi",
      "Pehmeät muodot",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  11: {
    images: ["/soft-minimalist-neutral-circles.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Pehmeät ympyrämuodot",
      "Neutraalit pastellisävyt",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  12: {
    images: ["/vintage-terracotta-warm-abstract.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Vintage-tyylinen kompositio",
      "Lämpimät terrakottasävyt",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
  13: {
    images: ["/vibrant-colorful-geometric-retro.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Rohkeat eloisat värit",
      "Geometriset retro-muodot",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "34,90 €", priceInCents: 3490 },
    ],
  },
}
