import type { Product, ProductDetails } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Pysähdy Hetkeksi",
    image: "/black-white-woman-hands-stop-gesture.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Mustavalkoinen minimalistinen taide, jossa nainen pitää käsiä kasvojensa edessä",
  },
  {
    id: 2,
    name: "Punainen Piste",
    image: "/purple-abstract-red-dot-center.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Hypnoottinen violetti abstraktio punaisella pisteellä keskellä",
  },
  {
    id: 3,
    name: "Honey Power 1968",
    image: "/japanese-honey-power-vintage-fruit-poster.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Japanilainen vintage-juliste hedelmällä ja tekstillä 'Honey Power, Hold My Flower'",
  },
  {
    id: 4,
    name: "Niseko Mountain Resort",
    image: "/red-niseko-mountain-resort-poster.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Punainen vintage-hiihtojuliste Niseko-vuorelta, jossa lumi sataa",
  },
  {
    id: 5,
    name: "Yoshino Kirsikankukat",
    image: "/yoshino-mountain-cherry-blossom.webp",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Japanilainen vintage-juliste Yoshino-vuoresta ja kirsikankukista",
  },
  {
    id: 6,
    name: "Kaksoisaurinko",
    image: "/abstract-cerberus-two-suns.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Abstrakti Cerberus-hahmo kahden auringon alla, surrealistinen taide",
  },
  {
    id: 7,
    name: "Kukkien Tuoksu",
    image: "/green-flowers-quirky-text-art.webp",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Leikkisä moderni taide vihreine kukkineen ja hauskalla tekstillä",
  },
  {
    id: 8,
    name: "Mind Maze",
    image: "/hypnotic-mind-maze-psychedelic-art.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Hypnoottinen abstrakti taide, jossa lukee 'Mind Maze'",
  },
  {
    id: 9,
    name: "Filosofinen Kissa",
    image: "/cat-philosophical-text-poster.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Kissakuva tekstillä 'Whatever you think it is, it isn't'",
  },
  {
    id: 10,
    name: "Surrealistinen Kollaasi",
    image: "/surrealist-collage-cigarette-bananas.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Surrealistinen kollaasi tupakka-askista, banaaneista naamoineen, sudenkorennoista ja kukista",
  },
  {
    id: 11,
    name: "Tangerine",
    image: "/japanese-tangerine-movie-poster.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Japanilainen mustavalkoinen elokuvajuliste, jossa nainen ja teksti 'Tangerine'",
  },
  {
    id: 12,
    name: "Kintsugi",
    image: "/japanese-kintsugi-bowl-broken-beauty.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Japanilainen kulho tekstillä 'More beautiful for having been broken'",
  },
  {
    id: 13,
    name: "Muotojen Maailma",
    image: "/abstract-shapes-eyes-were-all-just-shapes.avif",
    price: "alk 12,90 €",
    priceInCents: 1290,
    description: "Abstrakti taide tekstillä 'We're all just shapes', aukkoja joissa silmät",
  },
]

export const productDetails: Record<number, ProductDetails> = {
  1: {
    images: ["/black-white-woman-hands-stop-gesture.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Minimalistinen mustavalkoinen taide",
      "Moderni ja ajaton ilme",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  2: {
    images: ["/purple-abstract-red-dot-center.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Hypnoottinen violetti abstraktio",
      "Punainen keskipiste luo fokuksen",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  3: {
    images: ["/japanese-honey-power-vintage-fruit-poster.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Japanilainen vintage-tyyli",
      "Retro 1968 -estetiikka",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  4: {
    images: ["/red-niseko-mountain-resort-poster.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Vintage hiihtojuliste",
      "Japanilainen vuoristomaisema",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  5: {
    images: ["/yoshino-mountain-cherry-blossom.webp"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Japanilainen vintage-juliste",
      "Kirsikankukat ja vuorimaisema",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  6: {
    images: ["/abstract-cerberus-two-suns.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Abstrakti Cerberus-hahmo",
      "Surrealistinen kaksoisaurinko",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  7: {
    images: ["/green-flowers-quirky-text-art.webp"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Leikkisä moderni taide",
      "Vihreät käsinpiirretyt kukat",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  8: {
    images: ["/hypnotic-mind-maze-psychedelic-art.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Hypnoottinen abstrakti taide",
      "Mind Maze -teksti",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  9: {
    images: ["/cat-philosophical-text-poster.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Filosofinen kissakuva",
      "Ajatuksia herättävä teksti",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  10: {
    images: ["/surrealist-collage-cigarette-bananas.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Surrealistinen kollaasi",
      "Ainutlaatuinen yhdistelmä elementtejä",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  11: {
    images: ["/japanese-tangerine-movie-poster.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Japanilainen elokuvajuliste",
      "Mustavalkoinen dramaattinen taide",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  12: {
    images: ["/japanese-kintsugi-bowl-broken-beauty.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Japanilainen Kintsugi-filosofia",
      "Inspiroiva viesti kauneudesta",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
  13: {
    images: ["/abstract-shapes-eyes-were-all-just-shapes.avif"],
    materials: "Laadukas puuvillakangas, ympäristöystävällinen Giclee-muste",
    dimensions: "Saatavilla useissa koossa",
    care: "Suojaa suoralta auringonvalolta ja kosteudelta. Kehystäminen suositeltavaa.",
    shipping: "Ilmainen toimitus kaikkiin maihin. Toimitus 2-4 viikkoa. Pakattu huolellisesti suojaputkeen.",
    features: [
      "Laadukas puuvillakangas",
      "Ympäristöystävällinen Giclee-muste",
      "Rullalle rullattu kangas ilman kehystä",
      "Filosofinen abstrakti taide",
      "Ainutlaatuiset muodot ja silmät",
    ],
    sizes: [
      { name: "20x30 cm", dimensions: "20 x 30 cm", price: "alk 12,90 €", priceInCents: 1290 },
      { name: "30x42 cm", dimensions: "30 x 42 cm", price: "alk 19,90 €", priceInCents: 1990 },
      { name: "40x50 cm", dimensions: "40 x 50 cm", price: "alk 27,90 €", priceInCents: 2790 },
      { name: "40x60 cm", dimensions: "40 x 60 cm", price: "alk 29,90 €", priceInCents: 2990 },
      { name: "50x70 cm", dimensions: "50 x 70 cm", price: "alk 34,90 €", priceInCents: 3490 },
    ],
  },
}
